show_for_members:
  type: bool
  default: true
  description: 
    en: 'Display the banner for users logged into the forum'
show_for_anon:
  type: bool
  default: true
  description: 
    en: 'Display the banner for anonymous users'
display_on_mobile:
  type: bool
  default: true
  description: 
    en: 'Display the banner on mobile devices'
display_on_desktop:
  type: bool
  default: true
  description: 
    en: 'Display the banner on desktop computers'
display_on_homepage:
  type: bool
  default: true
  description: 
    en: 'Display the banner on the homepage'
url_must_contain:
  type: list
  list_type: simple
  default: /latest|/categories|/new|/unread|/top*|/tag/*|/tags/*|/c/*|/t/*
  description: 
    en: 'Enter paths that should display the banner. Add <code>*</code> to the end of the path as a wildcard'
dismissible:
  type: bool
  default: true
  description: 
    en: 'Allow the banner to be closed by users'
collapsible:
  type: bool
  default: true
  description: 
    en: 'Allow the banner to be expanded and collapsed by users'
default_collapsed_state:
  type: enum
  default: collapsed
  choices:
    - expanded
  description: 
    en: 'Default collapsed state when collapsible setting is enabled'
cookie_lifespan:
  type: enum
  default: none
  choices:
    - minute
    - day
    - week
    - month
    - year
  description: 
    en: 'The lifespan of the cookie used to remember if the banner has been closed, expanded, or collapsed.
         If set to "none", NO cookies will be used with this component, and any previously created cookies 
         related to the banner will be deleted the next time a user performs a full page load. The values are 
         measured as a single unit, so setting "year" will be one year, "week" will be one week, etc.'
cookie_name:
  type: string
  default: "v1"
  description: 
    en: 'When important changes are made to the banner, you must change the cookie name to ensure all your users see the changes.'
full_width_banner:
  type: bool
  default: false
  description: 
    en: 'Display the banner at full browser width'
swap_default_positioning:
  type: bool
  default: false
  description:
    en: 'If there is another banner-related component active, use this to swap its position with the Versatile Banner'
banner_background_image:
  type: string
  default: ""
  description: 
    en: 'The source url for your background image. Tip: You can upload an image to your main theme and use the url from that, 
         but make sure that you do not use "Uploads" section of this component. Any uploads added to this component will be 
         deleted whenever it is updated.'
background_color:
  type: string
  default: "var(--tertiary-low)"
  description: 
    en: 'Used in place of a background image'
primary_text_color:
  type: string
  default: "var(--primary)"
  description:
    en: 'The main text color of the banner'
secondary_text_color:
  type: string
  default: "var(--instagram)"
  description:
    en: 'The text color of the icon and text headings, and the button background color.'
link_text_color:
  type: string
  default: "var(--quaternary)"
  description:
    en: 'The text color links within the banner.
        <br><br><br>
        <h2>Banner Content Customization</h2>
        Customize the content of the banner with HTML. If you need to style your custom content 
        with CSS, create a separate theme component. Leave the content blank to exclude a column. 
        While a fourth column is provided, it will likely result in too much content for the 
        available space. Be sure you are happy with your configuration across different brower widths.'
main_heading_content:
  type: string
  textarea: true
  default: |
            <h2 class="x-title">ようこそ 🎉 iCute JP 掲示板</h2>
            <div class="colored-line"></div>
            <div class="description">
              <p>
                ネット上の話題・ネタを紹介、注目のニュースをまとめ読み！！
              </p>
            </div>
            <div class="colored-line"></div>
first_column_content:
  type: string
  textarea: true
  default: |
          <div class="buttons" id="my-button-1">
            <a href="/signup" class="btn btn-icon-text" style="color:#f2f2f2;font-size:1em;font-weight: bold;border-radius: 15px;">無料登録</a>
          </div>
second_column_content:
  type: string
  textarea: true
  default: |
          <div class="buttons" id="my-button-2" >
            <a href="/login" class="btn btn-icon-text" style="color:#f2f2f2;font-size:1em;font-weight: bold;border-radius: 15px;">ログイン</a>
          </div>
third_column_content:
  type: string
  textarea: true
  default: |
          <div class="buttons" id="my-button-3">
            <a href="/w/ads" class="btn btn-icon-text" style="color:#f2f2f2;font-size:1em;font-weight: bold;border-radius: 15px;">広告掲載</a>
          </div>
fourth_column_content:
  type: string
  textarea: true
  default: ''
  description:
    en: '<br><br>
        <h2>Column Sizes</h2>
        Use a percentage to make columns more wide or narrow. When set to "auto", the column will fill the 
        available space evenly with other "auto" columns.'
first_column_size:
  type: string
  default: 'auto'
second_column_size:
  type: string
  default: 'auto'
third_column_size:
  type: string
  default: 'auto'
fourth_column_size:
  type: string
  default: ''
  description: 
    en: '<br><br>
        <h2>Column Icons</h2>
        Use font awesome or a link to an image for the icon at the top of the columns.
        Accepted font awesome formats: <b>fa-icon</b>, <b>far fa-icon</b> or <b>fab fa-icon</b>. 
        <a href="https://fontawesome.com/icons?d=gallery&m=free" target="_blank">Click Here</a> 
        to view the list of available icons.'
first_column_icon:
  type: string
  default: 'gifts'
second_column_icon:
  type: string
  default: 'store'
third_column_icon:
  type: string
  default: 'handshake'
fourth_column_icon:
  type: string
  default: ''
